Repository GoogleCloudPlatform/gke-network-policy-demo, pull requests merged in 2020-06, with the labels that each got.

#36 update apiVersion of Deployment from extensions/v1beta1 to apps/v1
  README-QWIKLABS.md
  README.md
  manifests/hello-app/hello-server.yaml
Labels: cla: yes

#34 Fix OOM on bastion VM
  terraform/variables.tf
Labels: cla: yes, gke-helmsman, size/XS

#32 Fix deprecation notice for "zone"
  terraform/main.tf
Labels: cla: yes, gke-helmsman, size/XS

#30 Updating make.sh for terraform 0.12.x
  test/make.sh
Labels: approved, cla: yes, gke-helmsman, size/XS
